version: '3.7'

networks:
  test-net:

services:

  chrome:
    image: alpeware/chrome-headless-trunk
    logging:
      driver: "none"
    ports:
      - "9222"
    networks:
      - test-net

  test:
    image: demiurg/fl_test_perl
    build: .
    environment:
      USER: ${USER}
      PASSWORD: ${PASSWORD}
#    entrypoint: ["bash", "-c", "sleep 2073600"]
    entrypoint: ["./t/1.pl"]
    volumes:
      - "./t:/srv/autotest/t"
    networks:
      - test-net
