version: '3.1'

networks:
  test-net:

services:

  chrome:
    image: justinribeiro/chrome-headless
    cap_add:
      - SYS_ADMIN
    networks:
      - test-net
    restart: always

  test:
    image: demiurg/fl_test_perl
    depends_on:
      - chrome
    networks:
      - test-net
    restart: always
