version: '3.7'

networks:
  test-net:

services:

  chrome:
    image: justinribeiro/chrome-headless
    cap_add:
      - SYS_ADMIN
    networks:
      - test-net
    restart: always

  test:
    image: demiurg/fl_test_perl
    build: .
#    depends_on:
#      - chrome
    networks:
      - test-net
    restart: always
