version: '3.7'

networks:
  test-net:

services:

  chrome:
    image: alpeware/chrome-headless-trunk
    logging:
      driver: "none"
    ports:
      - "9222"
    networks:
      - test-net

  test:
    image: demiurg/fl_test_perl
    environment:
      FL_USER: ${FL_USER}
      PASSWORD: ${FL_PASSWORD}
    entrypoint: ["./t/1.pl"]
    volumes:
      - "./t:/srv/autotest/t"
    networks:
      - test-net
